### PR TITLE
Extracted file-naming and class-naming into their own methods

### PR DESCRIPTION
**Pull request by jonnyreeves**
Hey @sbrandwoo; this is something I knocked together to satisfy #14; let me know if this works for you :)

### CODE REVIEW

**Comment by sbrandwoo** [comment]
Looks good to me :thumbsup:

**Comment by jonnyreeves** [comment]
Cheers!  I should add some test-coverage for the classNamer before we merge this.

**Comment by jonnyreeves** [comment]
OK, now we have the ability to specify a `testNamer` as well :)  I've modified the unit tests to provide decent coverage of these options and created a 'customer_namer' suite which replicates the current / original behaviour. 

Please let me know if you're happy with this and I can get it merged, bump the version and update the history  in the README :cake:

**Comment by sbrandwoo** [comment]
I am happy :smiley_cat:

**Pull request merged**
