### PR TITLE
Prepare 0.3.0 release

### PR DESCRIPTION
**Pull request by jonnyreeves**
Removed beta warning; re-ordered changelog.

### CODE REVIEW

**Comment by jonnyreeves** [comment]
@sbrandwoo; hey Steve if you're happy for me to do releases, would you mind adding me so I can push to NPM? https://www.npmjs.com/profile/jonnyreeves

**Comment by sbrandwoo** [comment]
I'm trying, but NPM is not being very nice to me, and I can't log in. Will try again tomorrow.

**Comment by sbrandwoo** [comment]
Ok, that's done. For some reason the password changes don't work unless I'm in incognito mode... super weird but at least you're added now.

**Comment by jonnyreeves** [comment]
Cheers @sbrandwoo; are you happy for me to orchestrate future releases or would you like me to give you a heads up via PRs, etc first?

**Pull request merged**
